server.port: 8181
spring:
  application:
    name: kafka-consumer-example
  kafka:
    bootstrap-servers:
    - localhost:19092
    - localhost:29092
    - localhost:39092
    consumer:
      group-id: kp-grp-1
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: io.github.kprasad99.kafka.serde.KafkaProtobufDeserializer
